# Generated by Django 6.0.7 on 2026-07-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='user_id',
            new_name='user',
        ),
    ]
